[versions]
agp = "8.0.2"
targetSdk = "33"
minSdk = "21"
compileSdk = "33"

activity = "1.7.0-alpha02"
appcompat = "1.5.1"
benchmark = "1.1.1"
composeBom = "2022.11.00"
constraintLayout = "2.1.4"
core = "1.9.0"
coroutines = "1.6.4"
curtains = "1.2.4"
dataStore = "1.0.0"
cardView = "1.0.0"
kotlin = "1.7.20"
lifecycle = "2.5.1"
material = "1.7.0"
profileInstaller = "1.2.2"
testExt = "1.1.4"
tracing = "1.1.0"
uiAutomator = "2.2.0"
recyclerView = "1.2.1"

androidxTest = "1.4.0"
espressoCore = "3.4.0"
jUnit = "4.13.2"

gaiax-release = "0.4.3"
gaiax-debug = "main-SNAPSHOT"

[libraries]
gaiax = { group = "com.github.alibaba.GaiaX", name = "GaiaX", version.ref = "gaiax-debug" }
gaiaxadapter = { group = "com.github.alibaba.GaiaX", name = "GaiaX-Adapter", version.ref = "gaiax-debug" }
gaiaxclienttostudio = { group = "com.github.alibaba.GaiaX", name = "GaiaX-ClientToStudio", version.ref = "gaiax-debug" }

recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardView" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "jUnit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
profile-installer = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileInstaller" }
squareup-curtains = { group = "com.squareup.curtains", name = "curtains", version.ref = "curtains" }
tracing = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "tracing" }
ui-automator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiAutomator" }
viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

benchmark = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "benchmark" }
benchmark-junit = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark" }

junit = { group = "junit", name = "junit", version.ref = "jUnit" }
test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "testExt" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTest" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTest" }

[plugins]

application = { id = "com.android.application", version.ref = "agp" }
benchmark = { id = "androidx.benchmark", version.ref = "benchmark" }
library = { id = "com.android.library", version.ref = "agp" }
test = { id = "com.android.test", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
